CREATE TABLE IF NOT EXISTS players (
    id VARCHAR(255) PRIMARY KEY,
    wallet_id VARCHAR(255) UNIQUE NOT NULL,
    balance DECIMAL(20,2) NOT NULL DEFAULT 0,
    currency VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS transactions (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    req_id VARCHAR(255) UNIQUE NOT NULL,
    player_id VARCHAR(255) NOT NULL,
    wallet_id VARCHAR(255) NOT NULL,
    round_id VARCHAR(255) NOT NULL,
    session_id VARCHAR(255) NOT NULL,
    game_code VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    amount DECIMAL(20,2),
    currency VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (player_id) REFERENCES players(id),
    FOREIGN KEY (wallet_id) REFERENCES players(wallet_id)
);

    -- İndeksler
CREATE INDEX IF NOT EXISTS idx_transactions_player_id ON transactions(player_id);
CREATE INDEX IF NOT EXISTS idx_transactions_session_id ON transactions(session_id);
CREATE INDEX IF NOT EXISTS idx_transactions_req_id ON transactions(req_id);
CREATE INDEX IF NOT EXISTS idx_transactions_wallet_round_type ON transactions(wallet_id, round_id, type);
