// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlayerResponse player response
//
// swagger:model PlayerResponse
type PlayerResponse struct {

	// Bakiye
	Balance float64 `json:"balance,omitempty"`

	// Para birimi
	Currency string `json:"currency,omitempty"`

	// Oyuncu ID'si
	ID string `json:"id,omitempty"`

	// Cüzdan ID'si
	WalletID string `json:"wallet_id,omitempty"`
}

// Validate validates this player response
func (m *PlayerResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this player response based on context it is used
func (m *PlayerResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlayerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlayerResponse) UnmarshalBinary(b []byte) error {
	var res PlayerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
